services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'
  web:
    build: .
    ports:
      - '8080:8080'
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - TW_TOKEN=${TW_TOKEN}
    volumes:
      - .:/code
