services:
  web:
    build: .
    ports:
      - '80:80'
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - TW_TOKEN=${TW_TOKEN}
    volumes:
      - .:/code
